POST http://localhost:4004/odata/v4/leave/Departments
Content-Type: application/json

{
    "name": "SAP CAPM"
}

###
GET http://localhost:4004/odata/v4/leave/Departments

###
GET http://localhost:4004/odata/v4/leave/Employees?$expand=department

###
POST http://localhost:4004/odata/v4/leave/Employees
Content-Type: application/json

{
    "employeeId": "EMP101",
    "name": "Prathmesh",
    "designation": "Project Manager",
    "joiningDate": "2025-01-01",
    "department_ID": "85a00930-5bfe-435f-9211-eeff8e09d152"
}

###
POST http://localhost:4004/odata/v4/leave/Employees
Content-Type: application/json

{
    "employeeId": "EMP104",
    "name": "Yash",
    "designation": "Software Engineer",
    "joiningDate": "2026-01-01",
    "department_ID": "931116ca-7a40-417e-a9b7-2345e8046e2a",
    "manager_ID": "931116ca-7a40-417e-a9b7-2345e8046e2a"
}

###
GET http://localhost:4004/odata/v4/leave/Employees?$expand=manager

###
GET http://localhost:4004/odata/v4/leave/employeesByManager(managerID=6385c6b4-a10f-4e20-b887-7efab8138135)